-- MySQL Script generated by MySQL Workbench
-- Tue Dec  1 10:54:17 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Quickvey19
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Quickvey19
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Quickvey19` ;
USE `Quickvey19` ;

-- -----------------------------------------------------
-- Table `Quickvey19`.`Encuestadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Quickvey19`.`Encuestadores` (
  `idEncuestador` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `profesion` VARCHAR(50) NOT NULL,
  `encuestasRealizadas` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEncuestador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Quickvey19`.`Encuestados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Quickvey19`.`Encuestados` (
  `idEncuestado` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `idEncuestador` INT(11) NOT NULL,
  `sexo` VARCHAR(15) NOT NULL,
  `edad` INT(2) NOT NULL,
  `fechaRealizacion` DATE NOT NULL,
  PRIMARY KEY (`idEncuestado`),
  INDEX `idEncuestador_idx` (`idEncuestador` ASC) VISIBLE,
  CONSTRAINT `idEncuestador`
    FOREIGN KEY (`idEncuestador`)
    REFERENCES `Quickvey19`.`Encuestadores` (`idEncuestador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Quickvey19`.`Respuestas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Quickvey19`.`Respuestas` (
  `idRespuestas` INT(11) NOT NULL,
  `idEncuestado` INT(11) NOT NULL,
  `Pregunta1` VARCHAR(70) NOT NULL,
  `Pregunta2` VARCHAR(70) NOT NULL,
  `Pregunta3` VARCHAR(70) NOT NULL,
  `Pregunta4` VARCHAR(70) NOT NULL,
  `Pregunta5` VARCHAR(70) NOT NULL,
  `Pregunta6` VARCHAR(70) NOT NULL,
  `Pregunta7` VARCHAR(70) NOT NULL,
  `Pregunta8` VARCHAR(70) NOT NULL,
  `Pregunta9` VARCHAR(70) NOT NULL,
  `Pregunta10` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`idRespuestas`),
  INDEX `idEncuestado_idx` (`idEncuestado` ASC) VISIBLE,
  CONSTRAINT `idEncuestado`
    FOREIGN KEY (`idEncuestado`)
    REFERENCES `Quickvey19`.`Encuestados` (`idEncuestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
